title: Wu Lin
description: Research machine learning. Learn math and physics.
url: "https://yorkerlin.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-scholar

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - notebooks
  - embedded
