name: Lint

on:
  push:
    branches-ignore:
    - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      run: |
        find . \
            -type f \
            -name 'Dockerfile*' \
            -exec docker run --rm -i -v "$(pwd)":/mnt -w /mnt hadolint/hadolint:v1.17.2 hadolint '{}' \;
